[package]
name = "rolify-sqlx"
version.workspace = true
edition = "2024"
rust-version = "1.94"
license = "MIT"

[dependencies]
rolify-core = { workspace = true }
thiserror = { workspace = true }
sqlx = { workspace = true, features = ["uuid"] }
uuid = { workspace = true }

[dev-dependencies]
rolify-test = { workspace = true, features = ["suite"] }
testcontainers = "=0.27.3"
testcontainers-modules = { version = "=0.15.0", default-features = false, features = ["postgres", "mysql"] }
tokio = { workspace = true }
rstest = { workspace = true }
pretty_assertions = { workspace = true }
maybe-async = { workspace = true }

[features]
default = []
postgres = ["sqlx/postgres"]
mysql = ["sqlx/mysql"]
sqlite = ["sqlx/sqlite"]
suite = ["rolify-test/suite"]

[lints]
workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
