[package]
name = "rolify-test"
version.workspace = true
edition = "2024"
rust-version = "1.85"
license = "MIT"

[dependencies]
maybe-async.workspace = true
rolify-core = { path = "../rolify-core" }
rstest = { workspace = true, optional = true }
faker-rust = { version = "0.1", optional = true }

[features]
default = []
is_sync = ["maybe-async/is_sync", "rolify-core/is_sync"]
faker = ["dep:faker-rust"]
suite = ["dep:rstest", "dep:faker-rust"]

[dev-dependencies]
pretty_assertions.workspace = true
tokio.workspace = true

[lints]
workspace = true
